POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Blog with auth",
    "author": "Test Author",
    "url": "http://testblog.com",
    "likes": 5,
    "userId": "69602a1495527e24776e2d0b"
}
###
