POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "manikishan",
    "name": "Manikishan Ghantasala",
    "password": "password123"
}

